package rules.Assignment.GlobalJobAssignmentRules_dir

@gw.rules.RuleName("Assign Underwriter")
internal class AssignUnderwriter {
  static function doCondition(job : entity.Job) : boolean {
    
/*start00rule*/
return job.CurrentRoleAssignment.Role == TC_UNDERWRITER
/*end00rule*/

  }

  static function doAction(job : entity.Job, actions : gw.rules.Action) {

/*start00rule*/
/* Use child rules to select an underwriter */
/*end00rule*/

  }
}
